### ISSUE TITLE
Question about your code

### ISSUE THREAD

**Issue by azurons** [fclaerho/os10#1]
Hi,
I hope i don't bother you but i have a little question about your code,
why do you write ".start  ......"  and not " .start: ......" i noticed that you did it for other function
and i don't understand well why omit  " : " because for me it doesn't work without (with Nasm)

Thanks!
(And by the way you did a really great job, thank you)

**Comment by fclaerho** [comment]
Thanks for your message.

You're right, it's a syntax error.

I know I did compile and test os10 so it does work, but this is an old project and I'm not sure I dig out the very last version of the files, apparently not...

**Comment by fclaerho** [comment]
Alright, nasm was indeed complaining, labels are now fixed.
I also added a Makefile to build the images.

**Comment by azurons** [comment]
Salut ami français,
J'aimerai savoir si tu connais un guide, ou bien une documentation pour hardcoder un bootloader pour qu'au démarrage il se lance et lance un kernel linux/initrd.
Encore merci pour ton travail et ta réponse.
(Et désolé, on ne peut pas envoyer de message privé sur github)

**Comment by fclaerho** [comment]
Hello...
Je n'ai rien sur ce cas spécifique, non, en général les tutoriels proposent un bootloader pour un O/S custom, e.g. http://www.osdever.net/tutorials/
